import streamlit as st


def page_project_hypothesis_body():
    st.write("### Project Hypotheses")

    st.warning(f"**Hypothesis 1**: The leaves of plants that contain powdery "
               f"mildew have clear signs of infection, typically white "
               f"powdery patches of fungus on the surface of the leaf, "
               f"differentiating them from healthy leaves.\n\n"
               f"**Validation** of hypothesis 1 was achieved using "
               f"exploratory data analysis methods. The 'mean' and 'standard "
               f"deviation' images for healthy cherry leaves and cherry "
               f"leaves that contain powdery mildew were plotted using 30 "
               f"images for each label. The pixel values were normalized and "
               f"a plot for average image and a plot for variability in the "
               f"images were created for both healthy and powdery_mildew "
               f"labelled images.\n\n"
               f"A plot of the differences between an average healthy cherry "
               f"leaf and a cherry leaf with powdery mildew was created by "
               f"first calculating the mean image for each label and then "
               f"calculating the difference between the mean images. A plot "
               f"of the results of each calculation was created to provide a "
               f"visual representation of the data at each stage of the "
               f"process. The contrast between the labels is highlighted by "
               f"the darker areas in the difference image and the "
               f"similarities highlighted by the lighter areas.\n\n"
               f"An image montage for healthy cherry leaves and "
               f"mildew-infested leaves was created using a subset of images "
               f"of each label.\n\n"
               f"**Conclusions**:\n"
               f"* Studying the mean and variability of images per label "
               f"highlighted that a mildew infected cherry leaves exhibit "
               f"more variation across the surface of the leaf. However, the "
               f"study did not highlight any distinct patterns that could be "
               f"used to intuitively differentiate between healthy and "
               f"infected leaves.\n"
               f"* Studying the difference between average healthy and "
               f"average powdery mildew cherry leaves did not highlight "
               f"patterns where we could intuitively differentiate one from "
               f"another.\n"
               f"* The image montage can be used to visually identify "
               f"differences between a healthy leaf and a mildew infected "
               f"one, and highlight typical signs of mildew infection.")

    st.info(f"**Hypothesis 2**: Using the ML system developed for this "
            f"project, Farmy and Food's employee's will not need to have the "
            f"botanical expertise needed to diagnose powdery mildew on cherry "
            f"leaf samples to correctly identify infected trees.\n\n"
            f"**Validation** of hypothesis 2 was achieved by creating a "
            f"convolutional neural network that is capable of distinguishing "
            f"between healthy and powdery mildew infected cherry tree leaves. "
            f"The model requires users to provide only an image of a cherry "
            f"tree leaf and will give a prediction of if the leaf is infected "
            f"with mildew or not.\n\n"
            f"**Conclusion**: The user does not need to provide any other "
            f"information to the model, therefore does not any botanical "
            f"expertise to successfully use the model.")

    st.success(f"**Hypothesis 3**: Reliable predictions can be made to "
               f"determine if a given leaf contains powdery mildew or is "
               f"healthy, with a degree of 97% accuracy.\n\n"
               f"**Validation** of hypothesis 3 was achieved using model "
               f"performance and classification metrics.\n\n"
               f"**Conclusions**:\n"
               f"* The model learning curves suggest the model learned well "
               f"as both the loss and accuracy plots for training and "
               f"validation data follow a similar path and are close to each "
               f"other.\n"
               f"* The evaluation of the model over the data test set gave a "
               f"generalized loss of less than 1% and accuracy of more than "
               f"99%, which more than satisfies the clients requirement of "
               f"97% accuracy.\n"
               f"* The confusion matrix plot shows that when testing the "
               f"model with the test set; 419 healthy leaves were correctly "
               f"predicted to be healthy, 3 healthy leaves were incorrectly "
               f"predicted to be mildew infected, and all 422 mildew infected "
               f"leaves were correctly predicted to be mildew infected, no "
               f"mildew infected leaves were incorrectly predicted to be "
               f"healthy.\n"
               f"* Recall/sensitivity rate is the percentage of the class "
               f"that was properly predicted. The classification report shows "
               f"that 99.3% of the healthy leaf images were correctly "
               f"predicted as healthy and 100% of the mildew infected leaf "
               f"images were correctly predicted as infected.\n"
               f"* Precision is the percentage of predictions related to a "
               f"class made were correct, or how many predictions of a "
               f"certain class were correct compared to the total number of "
               f"predictions of that class. The classification report shows "
               f"that the 100% of the healthy class predictions made were "
               f"correct and 99.3% of the powdery_mildew class predictions "
               f"were correct.\n"
               f"* The f1-score measures Recall and Precision together using "
               f"Harmonic Mean. It gives the average value for Recall and "
               f"Precision.\n"
               f"* ROC (Receiver Operating Characteristic) is a probability "
               f"curve and is used to calculate the AUC (Area Under Curve) "
               f"value. The AUC value represents the degree or measure of "
               f"separability, which is the models capability to distinguish "
               f"between classes. The AUC value achieved in this evaluation "
               f"report shows that the model has a high capability to "
               f"distinguish between classes.")
