import streamlit as st


def page_project_hypothesis_body():
    st.write("### Project Hypotheses")

    st.warning(f"**Hypothesis 1**: The leaves of plants that contain powdery "
    f"mildew have clear signs of infection, typically white powdery patches "
    f"of fungus on the surface of the leaf, differentiating them from "
    f"healthy leaves.\n\n"
    f"**Validation** of hypothesis 1 was achieved using exploratory data "
    f"analysis methods. The 'mean' and 'standard deviation' images for "
    f"healthy cherry leaves and cherry leaves that contain powdery mildew "
    f"were plotted using 30 images for each label. The pixel values were "
    f"normalized and a plot for average image and a plot for variability in "
    f"the images were created for both healthy and powdery_mildew labelled "
    f"images.\n\n"
    f"A plot of the differences between an average healthy cherry leaf and a "
    f"cherry leaf with powdery mildew was created by first calculating the "
    f"mean image for each label and then calculating the difference between "
    f"the mean images. A plot of the results of each calculation was created "
    f"to provide a visual representation of the data at each stage of the "
    f"process. The contrast between the labels is highlighted by the darker "
    f"areas in the difference image and the similarities highlighted by the "
    f"lighter areas.\n\nAn image montage for healthy cherry leaves and "
    f"mildew-infested leaves was created using a subset of images of each "
    f"label.\n\n"
    f"**Conclusions**:\n"
    f"* Studying the mean and variability of images per label highlighted "
    f"that a mildew infected cherry leaves exhibit more variation across the "
    f"surface of the leaf. However, the study did not highlight any distinct "
    f"patterns that could be used to intuitively differentiate between "
    f"healthy and infected leaves.\n"
    f"* Studying the difference between average healthy and average powdery "
    f"mildew cherry leaves did not highlight patterns where we could "
    f"intuitively differentiate one from another.\n"
    f"* The image montage can be used to visually identify differences between "
    f"a healthy leaf and a mildew infected one, and highlight typical signs "
    f"of mildew infection.")

    st.info(f"**Hypothesis 2**: Using the ML system developed for this "
    f"project, Farmy and Food's employee's will not need to have the "
    f"botanical expertise needed to diagnose powdery mildew on cherry leaf "
    f"samples to correctly identify infected trees.\n\n"
    f"**Validation** of hypothesis 2 was achieved by creating a "
    f"convolutional neural network that is capable of distinguishing between "
    f"healthy and powdery mildew infected cherry tree leaves. The model "
    f"requires users to provide only an image of a cherry tree leaf and will "
    f"give a prediction of if the leaf is infected with mildew or not.\n\n"
    f"**Conclusion**: The user does not need to provide any other "
    f"information to the model, therefore does not any botanical expertise to "
    f"successfully use the model.")

    st.success(f"**Hypothesis 3**: Reliable predictions can be made to "
    f"determine if a given leaf contains powdery mildew or is healthy, with a "
    f"degree of 97% accuracy.\n\n"
    f"**Validation** of hypothesis 3 was achieved using model performance "
    f"and classification metrics.\n\n"
    f"**Conclusions**:\n"
    f"* The model learning curves suggest the model learned well as both the "
    f"loss and accuracy plots for training and validation data follow a "
    f"similar path and are close to each other.\n"
    f"* The evaluation of the model over the data test set gave a generalized "
    f"loss of less than 1% and accuracy of more than 99%, which more than "
    f"satisfies the clients requirement of 97% accuracy.\n"
    f"* The confusion matrix plot shows that when testing the model with the "
    f"test set; 419 healthy leaves were correctly predicted to be healthy, 3 "
    f"healthy leaves were incorrectly predicted to be mildew infected, and "
    f"all 422 mildew infected leaves were correctly predicted to be mildew "
    f"infected, no mildew infected leaves were incorrectly predicted to be "
    f"healthy.\n"
    f"* Recall/sensitivity rate is the percentage of the class that was "
    f"properly predicted. The classification report shows that 99.3% of the "
    f"healthy leaf images were correctly predicted as healthy and 100% of the "
    f"mildew infected leaf images were correctly predicted as infected.\n"
    f"* Precision is the percentage of predictions related to a class made "
    f"were correct, or how many predictions of a certain class were correct "
    f"compared to the total number of predictions of that class. The "
    f"classification report shows that the 100% of the healthy class "
    f"predictions made were correct and 99.3% of the powdery_mildew class "
    f"predictions were correct.\n"
    f"* The f1-score measures Recall and Precision together using Harmonic "
    f"Mean. It gives the average value for Recall and Precision.\n"
    f"* ROC (Receiver Operating Characteristic) is a probability curve and is "
    f"used to calculate the AUC (Area Under Curve) value. The AUC value "
    f"represents the degree or measure of separability, which is the models "
    f"capability to distinguish between classes. The AUC value achieved in "
    f"this evaluation report shows that the model has a high capability to "
    f"distinguish between classes.")